---
- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest

- name: Creation user sql
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL'
    state: present

- name: Creation database
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
