---
- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest

- name: Creation user sql
  mysql_user:
    name: sql
    password: sql
    priv: '*.*:ALL'
    state: present

- name: Creation database
  mysql_db:
    name: my_wiki
    state: present